[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
trading_escrow = "5ZHtRgU8gaPUMjUkWBFjxNF9o5m7Cr4jJ71PXTiE6TKc"

[programs.devnet]
trading_escrow="5ZHtRgU8gaPUMjUkWBFjxNF9o5m7Cr4jJ71PXTiE6TKc"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "localnet"
# wallet = '~\.config\solana\id.json'

[provider]
cluster = "devnet"
wallet = "./deployer.json"


[scripts]
test = "yarn run ts-mocha --loader node_modules/ts-node/esm.mjs -p ../../tsconfig.json './tests/release_funds.test.ts'"
initialize = "node ./programs/trading_escrow/scripts/initialize.js"


[build]
build-backend = "sbf"
