[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
trading_escrow = "gv4Ep7vbpPgHfTkZbgb834Jyve2mH19iSqCsQy6oukn"

[programs.devnet]
trading_escrow = "gv4Ep7vbpPgHfTkZbgb834Jyve2mH19iSqCsQy6oukn"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "localnet"
# wallet = '~\.config\solana\id.json'

[provider]
wallet = "/mnt/d/INVESTMENT/stock_mar/stock/phantom-keypair.json"
cluster = "https://api.devnet.solana.com"

[scripts]
test = "yarn run ts-mocha --loader node_modules/ts-node/esm.mjs -p ../../tsconfig.json './tests/release_funds.test.ts'"



[build]
build-backend = "sbf"
